.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KQ 6 "28 January 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
KQ \- an adventure game
.SH SYNOPSIS
.B kq
.SH DESCRIPTION
.B KQ
is an adventure game in the spirit of old console games such as Secret of
Mana, Final Fantasy or Zelda.

You control an adventurer, to be chosen amongst eight differently
skilled characters (a warrior, a priest, a thief, etc.), across a
journey to find the magical Staff of Xenarum. Some subquests will be
available to you as well.

You can find money in several places, but mostly by fighting monsters
outside of towns. You can then spend this money in towns buying
equipment, weaponry, medicine, magical items, spells and many more.
Towns are also a common place to gather information or restore health.

You will be able to save your game, but only outside of towns and caves,
or in special areas known as "save spots".
.SH KEYS
.TP
.B Left, Right, Up, Down
move the player
.TP
.B Left Alt
the "Action" and "OK" button; can be used to activate items and validate
menu options
.TP
.B Left Ctrl
the "Cancel" button; used to escape from the current menu
.TP
.B Enter
bring up the character menu to use items, choose equipment, cast spells or
see your players' characteristics
.TP
.B Esc
bring up the load/save/configure menu
.BR
.SH AUTHOR
KQ was originally written by Josh Bolduc <jdb@mb.sympatico.ca>, and
was continued by people from the Allegro community, mostly Peter Hull
<peterhull90@users.sourceforge.net>, TeamTerradactyl
<teamterradactyl@users.sourceforge.net> and Chris Barry
<crbarry@mts.net>.

This manual page was written by Sam Hocevar <sam@zoy.org>, for the Debian
GNU/Linux system (but may be used by others).
