#ifndef __CONSTANTS
#define __CONSTANTS

enum eSize {
  TILE_W = 16U,
  TILE_H = 16U,

  ONSCREEN_TILES_W = 20U,
  ONSCREEN_TILES_H = 15U,

  KQ_SCREEN_W = TILE_W * ONSCREEN_TILES_W,
  KQ_SCREEN_H = TILE_H * ONSCREEN_TILES_H,

  KQ_SCALED_SCREEN_W = KQ_SCREEN_W << 1,
  KQ_SCALED_SCREEN_H = KQ_SCREEN_H << 1
};

#endif // __CONSTANTS
