/* Allegro datafile object indexes, produced by grabber v3.9.33 (CVS), djgpp */
/* Datafile: C:\JDB\KQSTUFF\SSPRITES.DAT */
/* Date: Tue May 15 16:31:41 2001 */
/* Do not hand edit! */

#define AAXE_PCX                         0      /* BMP  */
#define ABSORB_PCX                       1      /* BMP  */
#define AMACE_PCX                        2      /* BMP  */
#define ASWORD_PCX                       3      /* BMP  */
#define BLACK_PCX                        4      /* BMP  */
#define BLESS_PCX                        5      /* BMP  */
#define BLIND_PCX                        6      /* BMP  */
#define BLIZ1_PCX                        7      /* BMP  */
#define BLIZ2_PCX                        8      /* BMP  */
#define BOLT1_PCX                        9      /* BMP  */
#define BOLT2_PCX                        10     /* BMP  */
#define BOLT3_PCX                        11     /* BMP  */
#define CASTER2_PCX                      12     /* BMP  */
#define CONFUSE_PCX                      13     /* BMP  */
#define CURE_PCX                         14     /* BMP  */
#define DIFFUSE_PCX                      15     /* BMP  */
#define DOOM_PCX                         16     /* BMP  */
#define DRAIN_PCX                        17     /* BMP  */
#define ETHEREAL_PCX                     18     /* BMP  */
#define FLAME_PCX                        19     /* BMP  */
#define FLOOD_PCX                        20     /* BMP  */
#define GENERIC_PCX                      21     /* BMP  */
#define HEROISM_PCX                      22     /* BMP  */
#define HOLD_PCX                         23     /* BMP  */
#define ICUREHP_PCX                      24     /* BMP  */
#define ICUREMP_PCX                      25     /* BMP  */
#define IRESTORE_PCX                     26     /* BMP  */
#define LIFE_PCX                         27     /* BMP  */
#define LIFEG_PCX                        28     /* BMP  */
#define POISGAS_PCX                      29     /* BMP  */
#define QUAKE_PCX                        30     /* BMP  */
#define QUICKEN_PCX                      31     /* BMP  */
#define RASP_PCX                         32     /* BMP  */
#define RESTORE_PCX                      33     /* BMP  */
#define RUNEOFA_PCX                      34     /* BMP  */
#define RUNEOFE_PCX                      35     /* BMP  */
#define RUNEOFF_PCX                      36     /* BMP  */
#define RUNEOFI_PCX                      37     /* BMP  */
#define SBLAST_PCX                       38     /* BMP  */
#define SCORCH_PCX                       39     /* BMP  */
#define SHELL_PCX                        40     /* BMP  */
#define SHIELD_PCX                       41     /* BMP  */
#define SLEEP_PCX                        42     /* BMP  */
#define SLOW_PCX                         43     /* BMP  */
#define STONE_PCX                        44     /* BMP  */
#define STONEGAS_PCX                     45     /* BMP  */
#define VENOM1_PCX                       46     /* BMP  */
#define WHIRL_PCX                        47     /* BMP  */
#define WHITE_PCX                        48     /* BMP  */
#define XSURGE_PCX                       49     /* BMP  */
